#!/usr/bin/env python3
"""report.py -- turn results/*.json into results/REPORT.md (tables of what was measured; no interpretation)."""
import json, os
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'results')
L = lambda n: json.load(open(os.path.join(R, n + '.json')))
pc = lambda v: f'{100 * v:.1f}%' if isinstance(v, (int, float)) else str(v)
out = ['# Measured results (generated by report.py from results/*.json)\n']
s = L('stage1'); out += ['## Stage 1: clone divergence', '', '| check | result |', '|---|---|',
    f"| identical at start (canonical, A, B, C share one SHA-256) | {s['identical_at_start']} |",
    f"| A and B differ after different experiences | {s['A_differs_from_B']} |",
    f"| A and C (same experience, same seed) stay byte-identical | {s['A_equals_C_same_experience']} |",
    f"| A on its domain / on B's domain | {pc(s['accuracy']['A_on_domain0'])} / {pc(s['accuracy']['A_on_domain1'])} |",
    f"| B on its domain / on A's domain | {pc(s['accuracy']['B_on_domain1'])} / {pc(s['accuracy']['B_on_domain0'])} |",
    f"| canonical (untrained) on the two domains | {pc(s['accuracy']['canonical_on_domain0'])} / {pc(s['accuracy']['canonical_on_domain1'])} |",
    f"| inputs where A and B answer differently | {pc(s['fraction_of_domain0_inputs_where_A_and_B_disagree'])} |",
    f"| fresh processes reproduce the outputs from the files; files unchanged by use | {s['restart_identical_outputs']} / {s['sha256_unchanged_by_use']} |",
    f"| model file bytes | {s['model_bytes']} |", '']
s = L('stage2'); m = s['in_domain']; out += ['## Stage 2: ten specialists, routing, provenance', '', '| metric | value |', '|---|---|',
    f"| in-domain rows / task accuracy / routing accuracy | {m['n']} / {pc(m['task_acc'])} / {pc(m['routing_acc'])} |",
    f"| unsupported (in-domain) / disagreement (k=3) | {pc(m['unsupported'])} / {pc(m['disagreement'])} |",
    f"| unsupported rate on three never-seen domains / on uniform noise | {pc(s['unknown_domains_unsupported_rate'])} / {pc(s['noise_unsupported_rate'])} |",
    f"| held-out accuracy of the ten specialists on their own data | {', '.join(pc(v['val_acc']) for v in s['specialists'].values())} |",
    '', 'Provenance records: `results/stage2_provenance.jsonl` (selected specialist, alternatives with relative distance, every contributing specialist with hash, class, confidence, weight).', '']
s = L('stage3'); out += ['## Stage 3: arbitration', '', '| condition | single specialist | arbitration (k=3) | disagreement exposed | accuracy on disagreements | accuracy on agreements |', '|---|---|---|---|---|---|']
for c, r in s['results'].items(): out.append(f"| {c} | {pc(r['single_specialist']['task_acc'])} | {pc(r['arbitration_k3']['task_acc'])} | {pc(r['disagreement_rate'])} | {pc(r['accuracy_on_disagreements'])} | {pc(r['accuracy_on_agreements'])} |")
out.append('')
s = L('stage4'); out += ['## Stage 4: composition (two device readings, answer = table of both states)', '', '| system | accuracy | bytes |', '|---|---|---|',
    f"| swarm: route each half, compose (unsupported {pc(s['swarm']['unsupported'])}) | {pc(s['swarm']['accuracy'])} | 10 specialists x 576 |"]
for k, v in s['baselines'].items(): out.append(f"| {k} ({v['train_rows']} rows, {v['epochs']} epochs) | {pc(v['accuracy'])} | {v['bytes']} |")
out += [f"| one specialist alone | {s['single_specialist_alone']} | |", '', f"Disclosure: {s['disclosure']}", '']
s = L('stage5'); m = s['measurements']; out += ['## Stage 5: dynamic library (10 specialists)', '', '| metric | value |', '|---|---|',
    f"| per-specialist model / metadata bytes | {m['per_specialist_model_bytes']} / {m['per_specialist_meta_bytes']} |",
    f"| index bytes (all routing data) / library storage bytes | {m['index_bytes']} / {m['storage_bytes']} |",
    f"| routing time per row / load+predict one row (fresh process, median) | {m['routing_seconds_per_row'] * 1e6:.1f} us / {m['load_and_predict_seconds_median'] * 1e3:.2f} ms |",
    f"| specialist process peak RSS / /bin/true floor / specialist working set | {m['specialist_process_peak_rss_kb']} KB / {m['true_process_peak_rss_kb']} KB / {m['specialist_working_set_bytes']} B |",
    f"| orchestrator (python+numpy) RSS | {m['orchestrator_rss_kb']} KB |",
    f"| resident specialists between calls (by construction) / active during a 1000-row batch | {m['resident_specialists_between_calls_by_construction']} / {s['batch']['active_specialists_during_batch']} |",
    f"| 1000-row batch: routing / pure uai32 subprocess time / python orchestration | {s['batch']['seconds']['routing'] * 1e3:.1f} ms / {s['batch']['seconds']['invocation'] * 1e3:.1f} ms / {s['batch']['seconds']['orchestration'] * 1e3:.1f} ms |", '']
s = L('stage6'); out += ['## Stage 6: scale', '', 'Monoliths are trained on the same 500 rows per domain and 60 epochs as each specialist (the capped equal-storage monolith at N >= 1000: 20 epochs, marked). "Equal storage" = N x 576-byte model files, metadata excluded; the swarm storage column includes metadata.', '',
    '| N | task acc | routing acc | unsupported | OOD unsupported | mini monolith 10-16-4 | equal model-storage monolith (NH, bytes, epochs) | swarm model B / storage B | routing us/row | uai32 subprocess ms/row | orchestration ms/row | build s |', '|---|---|---|---|---|---|---|---|---|---|---|---|']
for l in s['levels']:
    e = l['equal_storage_monolith']
    out.append(f"| {l['N']} | {pc(l['task_acc'])} | {pc(l['routing_acc'])} | {pc(l['unsupported'])} | {pc(l['out_of_distribution_unsupported_rate'])} | {pc(l['mini_monolith_10-16-4']['accuracy'])} | {pc(e['accuracy'])} ({e['hidden']}, {e['bytes']} B, {e['epochs']} ep{', capped' if e['capped'] else ''}) | {l['swarm_model_bytes_total']} / {l['swarm_storage_bytes']} | {l['routing_seconds'] / l['eval_rows'] * 1e6:.1f} | {l['invocation_seconds'] / l['eval_rows'] * 1e3:.3f} | {l['orchestration_seconds'] / l['eval_rows'] * 1e3:.3f} | {l['build_seconds']:.1f} |")
out += ['', '| N | swarm MACs/query (routing 2 per feature per specialist + one forward) | equal-storage monolith MACs/query | mini monolith MACs/query | eval processes | failed invocations (counted) | orchestrator RSS KB | specialist process RSS KB |', '|---|---|---|---|---|---|---|---|']
for l in s['levels']: out.append(f"| {l['N']} | {l['swarm_macs_per_query']} | {l['equal_storage_monolith']['macs_per_query']} | {l['mini_monolith_10-16-4']['macs_per_query']} | {l['eval_processes']} | {l['failed_invocations']} | {l['resources']['orchestrator_rss_kb']} | {l['resources']['specialist_process_peak_rss_kb']} |")
out.append('')
s = L('stage7'); out += ['## Stage 7: populations (five experts for one domain, five test conditions)', '', '| test condition | ' + ' | '.join(k.replace('expert_', '') for k in s['matrix']['normal']) + ' | swarm k=1 (selected) | swarm k=3 | oracle best |', '|---|' + '---|' * (len(s['matrix']['normal']) + 3)]
for c, row in s['matrix'].items():
    w = s['swarm'][c]; sel = max(w['selected_histogram'], key=w['selected_histogram'].get)
    out.append(f"| {c} | " + ' | '.join(pc(v) for v in row.values()) + f" | {pc(w['accuracy_k1'])} ({str(sel).replace('expert_', '')}) | {pc(w['accuracy_k3'])} | {pc(w['oracle_best_accuracy'])} ({w['oracle_best_expert'].replace('expert_', '')}) |")
out.append('')
s = L('stage8'); out += ['## Stage 8: learning over time', '', '| experiment | result |', '|---|---|',
    f"| continue training s0003 on new own-domain data: accuracy before / after; its hash changed; the other 9 files unchanged | {pc(s['continued_training']['s0003_before'])} / {pc(s['continued_training']['s0003_after'])}; {s['continued_training']['s0003_sha_changed']}; {s['continued_training']['others_unchanged']} |",
    f"| catastrophic forgetting: s0003 then trained on domain 7: accuracy on domain 3 / on domain 7 | {pc(s['forgetting']['s0003_on_domain3_after_learning_domain7'])} / {pc(s['forgetting']['s0003_on_domain7'])} |",
    f"| retrain s0003 from the canonical brain: accuracy on domain 3 (version) | {pc(s['retrained']['s0003_on_domain3'])} (v{s['retrained']['version']}) |",
    f"| corrupted s0005 detected by hash; its rows unsupported while corrupt; accuracy after replacement | {s['failed_expert']['verify_false']}; {pc(s['failed_expert']['rows_unsupported_while_corrupt'])}; {pc(s['failed_expert']['accuracy_after_replacement'])} |",
    f"| clone of s0002: same hash, identical outputs | {s['clone']['same_sha']}, {s['clone']['identical_outputs']} |",
    f"| branch s0002 into noisy and shifted descendants: all three hashes distinct | {s['branch']['all_distinct']} |",
    f"| parent / noisy branch on noisy data; parent / shifted branch on shifted data | {pc(s['branch']['accuracy']['parent_on_noisy'])} / {pc(s['branch']['accuracy']['noisy_branch_on_noisy'])}; {pc(s['branch']['accuracy']['parent_on_shifted'])} / {pc(s['branch']['accuracy']['shifted_branch_on_shifted'])} |",
    f"| removal: specialists before / after, file gone | {s['removal']['before']} / {s['removal']['after']}, {s['removal']['file_gone']} |", '']
s = L('stretch'); out += ['## Stretch: expert spawning', '', '| step | unsupported rate | buffered | spawned |', '|---|---|---|---|']
for r in s['steps']: out.append(f"| {r['step']} | {pc(r['unsupported_rate'])} | {r['buffer']} | {r.get('spawned', '')} ({r.get('from_rows', '')}) |")
f = s['final']; out += ['', f"Final: spawned {f['spawned']}; unsupported {pc(f['unsupported_rate'])}; accuracy {pc(f['accuracy'])} (domain 10: {pc(f['accuracy_domain10'])}, domain 11: {pc(f['accuracy_domain11'])}). {s['supervision']}", '']
open(os.path.join(R, 'REPORT.md'), 'w').write('\n'.join(out)); print('results/REPORT.md written')
